### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by Suburbanno** [vinz243/pTorrent#10]

**Comment by vinz243** [comment]
hey, didnt thought there would be still people interested! anyway I stopped development long ago, because I found it really diffcult to write unit tests and such, and the development is tedious because of that

**Comment by Suburbanno** [comment]
:(

**Comment by jacksonstauffer** [comment]
For what it’s worth, there’s still quite a few of us interested.

**Comment by Suburbanno** [comment]
yah
