### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by ghost** [vinz243/pTorrent#9]
please do a tutorial

**Comment by vinz243** [comment]
What do you want a tutorial for? Using it? It's not stable and far from it. Not even in alpha state...

**Comment by ghost** [comment]
then it does not work

**Comment by ghost** [comment]
Sorry for my english

**Comment by ghost** [comment]
Are you study it?

**Comment by vinz243** [comment]
it's not meant to work for now.

> Are you study it?

What do you mean? I don't undertsand sorry

**Comment by ghost** [comment]
Are you study Information Technology

**Comment by vinz243** [comment]
Ah IT. Nope. I will maybe tho.

**Comment by ghost** [comment]
How old are u?

**Comment by vinz243** [comment]
19 why does it matter?

**Comment by ghost** [comment]
No, i'm younger

**Comment by ghost** [comment]
to understand who I write

**Comment by ghost** [comment]
Are you on steam?

**Comment by vinz243** [comment]
Yeah same pseudo why

**Comment by ghost** [comment]
You haven't csgo

Il 06 nov 2016 3:53 PM, "vinz243" notifications@github.com ha scritto:

**Comment by vinz243** [comment]
lol I'm more a Battlefield 4 guy ;) where are you from?

**Comment by ghost** [comment]
Milan, Italy

Il 06 nov 2016 3:56 PM, "vinz243" notifications@github.com ha scritto:

**Comment by ghost** [comment]
Add me on steam (same pseudo) i don't like the pubblic chat

Il 06 nov 2016 3:59 PM, "Djgio 07" giorgiolongo07@gmail.com ha scritto:
